version: '3.8'

services:
  # Celery ワーカー（Windows用オーバーライド）
  worker:
    command: celery -A app.core.celery_app worker --loglevel=info --concurrency=4 --max-tasks-per-child=1000
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - C_FORCE_ROOT=1
    user: null  # userディレクティブを無効化

  # Celery Beat（Windows用オーバーライド）
  beat:
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - C_FORCE_ROOT=1
    user: null  # userディレクティブを無効化
