version: '3.8'

services:
  # Redis サービス
  redis:
    image: redis:7-alpine
    container_name: video_downloader_redis
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # FastAPI アプリケーション
  api:
    build: .
    container_name: video_downloader_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    volumes:
      - ./downloads:/app/downloads
      - ./logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Celery ワーカー（Linux/macOS対応版）
  worker:
    build: .
    container_name: video_downloader_worker
    command: celery -A app.core.celery_app worker --loglevel=info --concurrency=4 --max-tasks-per-child=1000 --uid=1000 --gid=1000
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    volumes:
      - ./downloads:/app/downloads
      - ./logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    user: "1000:1000"

  # Celery Beat
  beat:
    build: .
    container_name: video_downloader_beat
    command: celery -A app.core.celery_app beat --loglevel=info --scheduler=celery.beat:PersistentScheduler
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    volumes:
      - ./logs:/app/logs
      - ./celerybeat:/app/celerybeat
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    user: "1000:1000"

  # Flower
  flower:
    build: .
    container_name: video_downloader_flower
    command: celery -A app.core.celery_app flower --port=5555 --broker=redis://redis:6379/0
    ports:
      - "5555:5555"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  redis_data:
    driver: local

networks:
  default:
    name: video_downloader_network
